"""
Day 1 Task 1 — Data Audit Script
=================================
Run this before touching anything else.
Produces a full forensic report of your dataset:
  - Impossible/negative values
  - Class imbalance
  - Label leakage check (decision tree score)
  - Feature distributions per risk class
  - Outputs: outputs/audit_report.txt + outputs/audit_distributions.png

Usage:
    python src/audit.py
"""

import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

# ── paths ────────────────────────────────────────────────────────────────────
BASE  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA  = os.path.join(BASE, "data", "synthetic_athlete_health_risk.csv")
OUT   = os.path.join(BASE, "outputs")
os.makedirs(OUT, exist_ok=True)

FEATURES = [
    "age", "weight_kg", "bf_percent", "training_vol_hr_wk", "sleep_h",
    "testosterone_total", "estradiol", "ALT", "AST", "HDL", "LDL",
    "hematocrit", "creatinine", "mood_score", "libido_score", "enhancement_load",
]

# ── physiological bounds — anything outside = impossible ────────────────────
BOUNDS = {
    "creatinine":         (0.4,  5.0),
    "ALT":                (5,    200),
    "AST":                (5,    200),
    "HDL":                (15,   100),
    "LDL":                (50,   300),
    "hematocrit":         (28,   65),
    "testosterone_total": (50,   2500),
    "estradiol":          (5,    200),
    "enhancement_load":   (0.3,  2.0),
    "age":                (18,   65),
    "bf_percent":         (3,    50),
    "sleep_h":            (3,    12),
    "mood_score":         (1,    10),
    "libido_score":       (1,    10),
}


def run_audit():
    df = pd.read_csv(DATA)
    le = LabelEncoder()
    y  = le.fit_transform(df["risk"])

    lines = []
    def log(s=""): lines.append(s); print(s)

    log("=" * 65)
    log("  ENHANCED ATHLETE RISK PREDICTOR — DATA AUDIT REPORT")
    log("=" * 65)

    # ── 1. Basic shape ───────────────────────────────────────────────
    log("\n── 1. Dataset Shape ─────────────────────────────────────────")
    log(f"  Rows:     {len(df):,}")
    log(f"  Columns:  {df.shape[1]}")
    log(f"  Features: {len(FEATURES)}")

    # ── 2. Class balance ─────────────────────────────────────────────
    log("\n── 2. Class Balance ─────────────────────────────────────────")
    vc = df["risk"].value_counts()
    vn = df["risk"].value_counts(normalize=True)
    for cls in vc.index:
        bar = "█" * int(vn[cls] * 40)
        log(f"  {cls:10s}: {vc[cls]:5d}  ({vn[cls]*100:5.1f}%)  {bar}")
    if vn.max() > 0.5:
        log("  ⚠  Imbalanced — minority class < 15%. SMOTE required.")

    # ── 3. Impossible values ─────────────────────────────────────────
    log("\n── 3. Impossible / Out-of-Bounds Values ─────────────────────")
    total_bad = 0
    for col, (lo, hi) in BOUNDS.items():
        if col not in df.columns:
            continue
        neg  = (df[col] < lo).sum()
        high = (df[col] > hi).sum()
        bad  = neg + high
        total_bad += bad
        status = "✓" if bad == 0 else "✗"
        log(f"  {status} {col:25s} [{lo}, {hi}]  below={neg}  above={high}")
    log(f"\n  Total impossible values: {total_bad}")
    if total_bad > 0:
        log("  → Fix: clip to bounds in data_generator.py (Day 2)")

    # ── 4. Descriptive stats per feature ─────────────────────────────
    log("\n── 4. Feature Stats per Risk Class ──────────────────────────")
    key_feats = ["hematocrit", "ALT", "AST", "creatinine",
                 "enhancement_load", "testosterone_total", "HDL", "LDL"]
    header = f"  {'Feature':22s}  {'high':>16s}  {'moderate':>16s}  {'low':>16s}"
    log(header)
    log("  " + "-" * 74)
    for feat in key_feats:
        row = f"  {feat:22s}"
        for cls in ["high", "moderate", "low"]:
            sub = df[df["risk"] == cls][feat]
            row += f"  {sub.mean():6.1f} ± {sub.std():5.1f}"
        log(row)

    # ── 5. Leakage check ─────────────────────────────────────────────
    log("\n── 5. Label Leakage Check (Decision Tree) ───────────────────")
    X = df[FEATURES]
    dt4 = DecisionTreeClassifier(max_depth=4,  random_state=42).fit(X, y)
    dt8 = DecisionTreeClassifier(max_depth=8,  random_state=42).fit(X, y)
    dt16= DecisionTreeClassifier(max_depth=16, random_state=42).fit(X, y)
    log(f"  Depth  4 accuracy: {dt4.score(X,y):.4f}")
    log(f"  Depth  8 accuracy: {dt8.score(X,y):.4f}")
    log(f"  Depth 16 accuracy: {dt16.score(X,y):.4f}")
    if dt8.score(X, y) > 0.99:
        log("  ⚠  CONFIRMED: Labels are generated by a deterministic rule.")
        log("     Depth-8 tree achieves near-perfect accuracy.")
        log("     → Disclose in paper Section 2 (Dataset) as a synthetic benchmark.")
        log("     → This is NOT a flaw — it must be explicitly framed.")

    # ── 6. MLP scaling issue ─────────────────────────────────────────
    log("\n── 6. Feature Scale Variance (MLP Scaling Issue) ────────────")
    log(f"  {'Feature':25s}  {'min':>8s}  {'max':>8s}  {'range':>8s}")
    log("  " + "-" * 56)
    for feat in FEATURES:
        mn  = df[feat].min()
        mx  = df[feat].max()
        rng = mx - mn
        flag = "  ← WIDE RANGE" if rng > 500 else ""
        log(f"  {feat:25s}  {mn:8.2f}  {mx:8.2f}  {rng:8.2f}{flag}")
    log("  → MLP needs StandardScaler. All tree models are scale-invariant.")

    # ── 7. Sex imbalance note ────────────────────────────────────────
    log("\n── 7. Demographic Balance ───────────────────────────────────")
    log(df["sex"].value_counts().to_string())
    log(df["status"].value_counts().to_string())
    male_pct = (df["sex"] == "male").mean()
    if male_pct > 0.8:
        log(f"\n  ⚠  {male_pct*100:.0f}% male. Mention in paper Limitations section.")

    # ── 8. Summary verdict ───────────────────────────────────────────
    log("\n── 8. Summary — Issues to Fix Before Paper Submission ───────")
    log("  P1  Negative creatinine (448 rows) → clip in data_generator.py")
    log("  P2  Negative estradiol (3 rows)    → clip in data_generator.py")
    log("  P1  Negative AST (1 row)           → clip in data_generator.py")
    log("  P2  Label circularity              → disclose + NHANES validation")
    log("  P3  MLP missing StandardScaler     → Pipeline fix in train.py")
    log("  P4  Class imbalance 57/32/11       → SMOTE on train split only")
    log("  P5  requirements.txt duplicates    → deduplicate")

    log("\n" + "=" * 65)
    log("  Audit complete.")
    log("=" * 65)

    # ── Save report ──────────────────────────────────────────────────
    report_path = os.path.join(OUT, "audit_report.txt")
    with open(report_path, "w", encoding="utf-8") as f:

        f.write("\n".join(lines))
    print(f"\n  Report saved → {report_path}")

    # ── Plot distributions ───────────────────────────────────────────
    _plot_distributions(df)


def _plot_distributions(df):
    key_feats = [
        "hematocrit", "ALT", "creatinine", "enhancement_load",
        "testosterone_total", "HDL", "LDL", "AST",
    ]
    colors = {"high": "#E24B4A", "moderate": "#EF9F27", "low": "#1D9E75"}

    fig = plt.figure(figsize=(16, 10))
    fig.suptitle("Feature Distributions by Risk Class (Current Dataset — v1)",
                 fontsize=14, fontweight="bold", y=1.01)
    gs = gridspec.GridSpec(2, 4, hspace=0.45, wspace=0.35)

    for idx, feat in enumerate(key_feats):
        ax = fig.add_subplot(gs[idx // 4, idx % 4])
        for cls in ["low", "moderate", "high"]:
            data = df[df["risk"] == cls][feat].dropna()
            data.plot.kde(ax=ax, label=cls, color=colors[cls], linewidth=1.8)

        # Mark physiological bounds if available
        if feat in BOUNDS:
            lo, hi = BOUNDS[feat]
            ax.axvline(lo, color="grey", linestyle="--", linewidth=0.8, alpha=0.6)
            ax.axvline(hi, color="grey", linestyle="--", linewidth=0.8, alpha=0.6)

        # Highlight impossible values
        neg_count = (df[feat] < 0).sum()
        title_suffix = f"  [⚠ {neg_count} impossible]" if neg_count > 0 else ""
        ax.set_title(f"{feat}{title_suffix}", fontsize=10, fontweight="bold")
        ax.set_xlabel("")
        ax.tick_params(labelsize=8)
        ax.legend(fontsize=7, frameon=False)
        ax.set_ylabel("Density", fontsize=8)

    plt.tight_layout()
    out_path = os.path.join(OUT, "audit_distributions.png")
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Distributions plot saved → {out_path}")


if __name__ == "__main__":
    run_audit()